"""Generate reports/data_quality_report.md from the actual cached pipeline artifacts
(never hand-typed numbers) so it can't drift from what the pipeline actually produced."""
import json
import sys
from collections import Counter
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

ROOT = Path(__file__).resolve().parent.parent
PROCESSED = ROOT / "data" / "processed"
REPORTS = ROOT / "reports"
REPORTS.mkdir(exist_ok=True)


def main():
    markets = json.loads((PROCESSED / "markets_accepted.json").read_text())
    excluded = json.loads((PROCESSED / "markets_excluded.json").read_text())
    obs_exclusions = json.loads((PROCESSED / "observation_exclusions.json").read_text())
    obs = pd.read_parquet(PROCESSED / "observations.parquet")

    n_discovered = len(markets) + len(excluded)
    exclusion_counts = Counter(e["reason"] for e in excluded)
    obs_exclusion_counts = Counter(e["reason"] for e in obs_exclusions)
    by_horizon = obs.groupby("horizon_hours").size().sort_index(ascending=False)

    lines = []
    lines.append("# Data Quality Report\n")
    lines.append("Generated by `scripts/10_generate_reports.py` directly from the cached pipeline "
                  "artifacts in `data/processed/` — every number below reflects an actual run, not a "
                  "hand-typed estimate.\n")

    lines.append("## Market discovery\n")
    lines.append(f"- Markets discovered (Gamma `btc-up-or-down-daily` series scan): **{n_discovered}**")
    lines.append(f"- Accepted (resolved, passed structural + outcome validation): **{len(markets)}**")
    lines.append(f"- Excluded: **{len(excluded)}**\n")

    lines.append("### Exclusion reasons (market level)\n")
    lines.append("| Reason | Count |")
    lines.append("|---|---|")
    for reason, count in exclusion_counts.most_common():
        lines.append(f"| {reason} | {count} |")
    lines.append("")

    lines.append("### Exclusion reasons (observation/horizon level)\n")
    lines.append("| Reason | Count |")
    lines.append("|---|---|")
    for reason, count in obs_exclusion_counts.most_common():
        lines.append(f"| {reason} | {count} |")
    lines.append("")

    lines.append("## Observation dataset\n")
    lines.append(f"- Total fixed-horizon observations: **{len(obs)}**")
    lines.append(f"- Distinct markets represented: **{obs['slug'].nunique()}**")
    lines.append("")
    lines.append("| Horizon (hours) | N observations |")
    lines.append("|---|---|")
    for h, n in by_horizon.items():
        lines.append(f"| {h} | {n} |")
    lines.append("")

    lines.append("## Feature availability\n")
    lines.append(f"- News data available: **{obs['news_data_available'].mean():.1%}** of observations")
    lines.append(f"- Social data available: **{obs['social_data_available'].mean():.1%}** of observations")
    lines.append(f"- Median Polymarket price staleness at observation time: "
                  f"**{obs['price_staleness_sec'].median():.0f}s** "
                  f"(tolerance: {int(20*60)}s)")
    lines.append(f"- Median BTC price staleness at observation time: "
                  f"**{obs['btc_staleness_sec'].median():.0f}s** (tolerance: {int(15*60)}s)")
    lines.append(f"- `market_liquidity` == 0 for **{(obs['market_liquidity'] == 0).mean():.1%}** of observations "
                  "(see README 'Known limitations' — Gamma's AMM-liquidity field is unused by these CLOB markets; "
                  "market volume substitutes as the depth proxy throughout).")
    lines.append("")

    lines.append("## Outcome balance\n")
    up_frac = obs.drop_duplicates("slug")["outcome_up"].mean()
    lines.append(f"- Realized Up frequency across the {obs['slug'].nunique()} distinct resolved markets: "
                  f"**{up_frac:.1%}**\n")

    # --- Extended hourly sample (optional -- only if scripts 11-14 have run) ---
    hourly_markets_path = PROCESSED / "hourly_markets_accepted.json"
    hourly_excluded_path = PROCESSED / "hourly_markets_excluded.json"
    hourly_obs_path = PROCESSED / "hourly_observations.parquet"
    if hourly_markets_path.exists() and hourly_obs_path.exists():
        h_markets = json.loads(hourly_markets_path.read_text())
        h_excluded = json.loads(hourly_excluded_path.read_text()) if hourly_excluded_path.exists() else []
        h_obs = pd.read_parquet(hourly_obs_path)
        h_exclusion_counts = Counter(e["reason"] for e in h_excluded)
        h_by_horizon = h_obs.groupby("horizon_minutes").size().sort_index(ascending=False)

        lines.append("## Extended sample: hourly BTC Up/Down markets\n")
        lines.append("Replication-check sample used in `reports/research_memo.md` Part 4 and the dashboard's "
                      "\"6 · Extended Sample (Hourly)\" tab. Most recent N resolved markets (offset-pagination "
                      "cap), not the series' full history.\n")
        lines.append(f"- Markets discovered: **{len(h_markets) + len(h_excluded)}**")
        lines.append(f"- Accepted: **{len(h_markets)}** | Excluded: **{len(h_excluded)}**")
        lines.append(f"- Date range: **{min(m['start_date'] for m in h_markets)[:10]}** to "
                      f"**{max(m['end_date'] for m in h_markets)[:10]}**")
        lines.append(f"- Observations built: **{len(h_obs)}** across **{h_obs['slug'].nunique()}** markets\n")
        if h_exclusion_counts:
            lines.append("### Exclusion reasons\n")
            lines.append("| Reason | Count |")
            lines.append("|---|---|")
            for reason, count in h_exclusion_counts.most_common():
                lines.append(f"| {reason} | {count} |")
            lines.append("")
        lines.append("| Horizon (minutes) | N observations |")
        lines.append("|---|---|")
        for h, n in h_by_horizon.items():
            lines.append(f"| {h} | {n} |")
        lines.append("")

    (REPORTS / "data_quality_report.md").write_text("\n".join(lines))
    print(f"Wrote {REPORTS / 'data_quality_report.md'}")


if __name__ == "__main__":
    main()
